header = "\tvoid VOCAL_TRACT::update_A()"
doc ='''\n\t// This method is automatically generated by an external python
\t// script, not by pyphs\n'''
body = ""
N_lambda = 5

for i in range(N_lambda):
    for j in range(N_lambda):
        if i == j:
            body += f"\t\tA({i},{j}) = (*mu_{i+1}_add_mu_{i+2});\n"
        if j == i-1:
            body += f"\t\tA({i},{j}) = 0.5*(*mu_{i+1});\n"
        if j == i+1:
            body += f"\t\tA({i},{j}) = 0.5*(*mu_{i+2});\n"

method = header + '{' +  doc + body + "\t}"
prototype = header + ';'
print(prototype)
print("\n")
print(method)

